# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_pp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pp',
            field=models.ImageField(default='/static/globals/images/profile.jpg', upload_to='/static/globals/images'),
        ),
    ]
