# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170509_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pp',
            field=models.ImageField(default='/home/chimaobi/ws/Python/oes/static/globals/images/profile.jpg', upload_to='/home/chimaobi/ws/Python/oes/static/globals/images'),
        ),
    ]
