# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-17 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170509_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pp',
        ),
    ]
